"""Budget Forecasting Analyst: VPC, ECR, EFS, Fargate + ALB, S3, CloudFront, SSM (docs/aws-cdk-requirements.md)."""
from pathlib import Path

from aws_cdk import (
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
    aws_cloudfront as cloudfront,
    aws_cloudfront_origins as origins,
    aws_ec2 as ec2,
    aws_ecr as ecr,
    aws_ecs as ecs,
    aws_efs as efs,
    aws_elasticloadbalancingv2 as elbv2,
    aws_iam as iam,
    aws_logs as logs,
    aws_s3 as s3,
    aws_s3_deployment as s3deploy,
    aws_ssm as ssm,
)
from constructs import Construct

REPO_ROOT = Path(__file__).resolve().parents[2]

# CloudFront forwards /api/* to the ALB; the backend routes have no /api prefix, so strip it at the edge.
STRIP_API_PREFIX = """
function handler(event) {
  var r = event.request;
  r.uri = r.uri.replace(/^\\/api(\\/|$)/, '/');
  return r;
}
"""


class BudgetForecastingStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cpu = int(self.node.try_get_context("backend_cpu") or 1024)
        memory = int(self.node.try_get_context("backend_memory_mib") or 2048)

        # ---- T51: network and image repository
        vpc = ec2.Vpc(self, "Vpc", max_azs=2, nat_gateways=1)
        repo = ecr.Repository(
            self, "BackendRepo", repository_name="budget-forecasting-backend",
            removal_policy=RemovalPolicy.DESTROY, empty_on_delete=True,
        )

        # ---- T53: data + frontend buckets, SSM, logs
        data_bucket = s3.Bucket(
            self, "DataBucket", bucket_name=None,  # globally unique name generated by CloudFormation
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL, encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True, removal_policy=RemovalPolicy.DESTROY, auto_delete_objects=True,
        )
        frontend_bucket = s3.Bucket(
            self, "FrontendBucket", block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED, enforce_ssl=True,
            removal_policy=RemovalPolicy.DESTROY, auto_delete_objects=True,
        )

        model_param = ssm.StringParameter(
            self, "BedrockModelId", parameter_name="/budget-forecasting/bedrock-model-id",
            string_value=self.node.try_get_context("bedrock_model_id") or "SET-ME-after-deploy",
            description="Bedrock model or inference profile id. Update after deploy if needed.",
        )
        replay_param = ssm.StringParameter(
            self, "ReplayActive", parameter_name="/budget-forecasting/replay-active",
            string_value="false", description='"true" serves scripted replay traces and never calls Bedrock.',
        )
        log_group = logs.LogGroup(
            self, "BackendLogs", log_group_name="/ecs/budget-forecasting-backend",
            retention=logs.RetentionDays.ONE_WEEK, removal_policy=RemovalPolicy.DESTROY,
        )

        # ---- T52: EFS, cluster, Fargate service, ALB
        fs = efs.FileSystem(
            self, "DuckDbEfs", file_system_name="budget-forecasting-duckdb-efs", vpc=vpc, encrypted=True,
            removal_policy=RemovalPolicy.DESTROY,
        )
        access_point = fs.add_access_point(
            "DuckDbAccessPoint", path="/duckdb",
            create_acl=efs.Acl(owner_uid="1000", owner_gid="1000", permissions="755"),
            posix_user=efs.PosixUser(uid="1000", gid="1000"),
        )

        cluster = ecs.Cluster(self, "Cluster", cluster_name="budget-forecasting-cluster", vpc=vpc)

        task_def = ecs.FargateTaskDefinition(self, "BackendTask", cpu=cpu, memory_limit_mib=memory)
        task_def.add_volume(
            name="duckdb",
            efs_volume_configuration=ecs.EfsVolumeConfiguration(
                file_system_id=fs.file_system_id,
                transit_encryption="ENABLED",
                authorization_config=ecs.AuthorizationConfig(access_point_id=access_point.access_point_id, iam="ENABLED"),
            ),
        )
        container = task_def.add_container(
            "backend",
            image=ecs.ContainerImage.from_asset(
                str(REPO_ROOT), file="backend/Dockerfile.ecs",
                exclude=["venv", "**/node_modules", "frontend", "infra", "cdk.out", ".git", "tests", "docs", "**/__pycache__", ".env"],
            ),
            logging=ecs.LogDriver.aws_logs(stream_prefix="backend", log_group=log_group),
            environment={
                "DUCKDB_DATA_DIR": "/data/duckdb",
                "S3_DATASET_BUCKET": data_bucket.bucket_name,
                "AWS_DEFAULT_REGION": self.region,
            },
            secrets={
                "BEDROCK_MODEL_ID": ecs.Secret.from_ssm_parameter(model_param),
                "REPLAY_MODE": ecs.Secret.from_ssm_parameter(replay_param),
            },
            port_mappings=[ecs.PortMapping(container_port=8000)],
        )
        container.add_mount_points(ecs.MountPoint(container_path="/data/duckdb", source_volume="duckdb", read_only=False))

        # task role: Bedrock streaming, dataset bucket, SSM reads, EFS client access via the access point
        task_def.task_role.add_to_principal_policy(iam.PolicyStatement(
            actions=["bedrock:InvokeModelWithResponseStream", "bedrock:InvokeModel"], resources=["*"]))
        data_bucket.grant_read_write(task_def.task_role)
        model_param.grant_read(task_def.task_role)
        replay_param.grant_read(task_def.task_role)
        fs.grant_read_write(task_def.task_role)

        alb = elbv2.ApplicationLoadBalancer(
            self, "Alb", vpc=vpc, internet_facing=True, idle_timeout=Duration.seconds(310),
        )
        service = ecs.FargateService(
            self, "BackendService", cluster=cluster, task_definition=task_def, desired_count=1,
            assign_public_ip=False, platform_version=ecs.FargatePlatformVersion.LATEST,
            health_check_grace_period=Duration.seconds(60),
        )
        fs.connections.allow_default_port_from(service)
        listener = alb.add_listener("Http", port=80, open=True)
        listener.add_targets(
            "Backend", port=8000, protocol=elbv2.ApplicationProtocol.HTTP, targets=[service],
            health_check=elbv2.HealthCheck(path="/health", interval=Duration.seconds(30)),
            deregistration_delay=Duration.seconds(10),
        )

        # ---- T53: CloudFront (frontend from S3, /api/* to ALB) and frontend deployment
        strip_api = cloudfront.Function(
            self, "StripApiPrefix", code=cloudfront.FunctionCode.from_inline(STRIP_API_PREFIX),
            runtime=cloudfront.FunctionRuntime.JS_2_0,
        )
        api_origin = origins.HttpOrigin(
            alb.load_balancer_dns_name, protocol_policy=cloudfront.OriginProtocolPolicy.HTTP_ONLY,
            read_timeout=Duration.seconds(60),
        )
        distribution = cloudfront.Distribution(
            self, "Distribution", default_root_object="index.html",
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3BucketOrigin.with_origin_access_control(frontend_bucket),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            ),
            additional_behaviors={
                "/api/*": cloudfront.BehaviorOptions(
                    origin=api_origin,
                    allowed_methods=cloudfront.AllowedMethods.ALLOW_ALL,
                    cache_policy=cloudfront.CachePolicy.CACHING_DISABLED,
                    origin_request_policy=cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
                    viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
                    function_associations=[cloudfront.FunctionAssociation(
                        function=strip_api, event_type=cloudfront.FunctionEventType.VIEWER_REQUEST)],
                ),
            },
            # SPA fallback
            error_responses=[cloudfront.ErrorResponse(http_status=403, response_http_status=200, response_page_path="/index.html"),
                             cloudfront.ErrorResponse(http_status=404, response_http_status=200, response_page_path="/index.html")],
        )
        s3deploy.BucketDeployment(
            self, "DeployFrontend", sources=[s3deploy.Source.asset(str(REPO_ROOT / "frontend" / "dist"))],
            destination_bucket=frontend_bucket, distribution=distribution, distribution_paths=["/*"],
        )

        CfnOutput(self, "AlbDnsName", value=alb.load_balancer_dns_name)
        CfnOutput(self, "CloudFrontUrl", value=f"https://{distribution.distribution_domain_name}")
        CfnOutput(self, "DataBucketName", value=data_bucket.bucket_name)
        CfnOutput(self, "EcrRepositoryUri", value=repo.repository_uri)
