"""Recompute enhanced-dataset ground truth (docs: tests/ground_truth_enhanced.md).

Usage: python scripts/compute_ground_truth_enhanced.py > tests/ground_truth_enhanced.md
Convention: aggregates use include_in_totals = TRUE rows only (synthetic rows included).
"""
import pandas as pd, numpy as np, sys
path = sys.argv[1] if len(sys.argv) > 1 else "data/Team6Dataset_Enhanced 1.xlsx"
e = pd.read_excel(path)
a = e[e.include_in_totals].copy()
pct = lambda g: (g.actual_spend_usd.sum() / g.budgeted_amount_usd.sum() - 1) * 100
P = print

P("# Ground Truth (Enhanced) — generated by scripts/compute_ground_truth_enhanced.py\n")
P("Source: `data/Team6Dataset_Enhanced 1.xlsx`. Aggregates exclude `include_in_totals = FALSE` rows.\n")
P("## 1. Shape")
P(f"- rows: {len(e)}; include_in_totals TRUE: {len(a)}; synthetic: {int(e.is_synthetic.sum())}")
P(f"- departments: {e.department.nunique()}; categories: {e.budget_category.nunique()}; fund sources: {e.fund_source.nunique()}")
P(f"- non-synthetic distinct source_record_id: {e.source_record_id.nunique()}")
P(f"- forecast_accuracy_pct mean (all rows): {e.forecast_accuracy_pct.mean():.2f}; (include_in_totals): {a.forecast_accuracy_pct.mean():.2f}")
key7 = ["department","budget_category","fiscal_year","fiscal_quarter","month","fund_source","report_type"]
P(f"- 7-col key (dept,cat,FY,FQ,month,fund,report_type) duplicate rows: {int(e.duplicated(key7, keep=False).sum())}; unique combos: {len(e.drop_duplicates(key7))}")
key4 = ["department","budget_category","fiscal_year","fiscal_quarter"]
d4 = e[~e.is_synthetic].groupby(key4).source_record_id.nunique()
P(f"- non-synthetic 4-col (dept,cat,FY,FQ) combos with >1 distinct source_record_id: {int((d4>1).sum())} covering {int(d4[d4>1].sum())} source records")
P("\n## 2. Aggregate variance % (actual/budget − 1)\n")
P("### Fiscal year"); [P(f"- {k}: {pct(g):.2f}") for k, g in a.groupby("fiscal_year")]
P("\n### Category"); [P(f"- {k}: {pct(g):.2f}") for k, g in a.groupby("budget_category")]
P("\n### Department"); [P(f"- {k}: {pct(g):.2f}") for k, g in a.groupby("department")]
P("\n## 3. Quarterly spend-vs-budget ratio\n")
q = a.groupby(["fiscal_year","fiscal_quarter"]).apply(lambda g: g.actual_spend_usd.sum()/g.budgeted_amount_usd.sum())
for (fy, fq), v in q.items(): P(f"- {fy} {fq}: {v:.4f}")
P("\n## 4. Persistent patterns (|agg var| ≥ 5% same sign in ≥2 of 3 FY)\n")
for col, lab in (("budget_category","category"),("department","department")):
    for ent, g in a.groupby(col):
        yr = {fy: pct(s) for fy, s in g.groupby("fiscal_year")}
        over = [y for y,v in yr.items() if v >= 5]; under = [y for y,v in yr.items() if v <= -5]
        for d, ys in (("over",over),("under",under)):
            if len(ys) >= 2:
                P(f"- {lab} | {ent} | {d} | qualifying {', '.join(sorted(ys))} | " + ", ".join(f"{y}={v:+.1f}" for y,v in sorted(yr.items())))
P("\n## 5. Quarters of data per entity (STL gating needs ≥ 8)\n")
for col, lab in (("budget_category","category"),("department","department")):
    n = a.groupby(col).apply(lambda g: g[["fiscal_year","fiscal_quarter"]].drop_duplicates().shape[0])
    short = n[n < 8]
    P(f"- {lab}: entities with < 8 quarters: " + (", ".join(f"{k} ({v})" for k, v in short.items()) or "none"))
P("\n## 6. Anomaly detection (hybrid: |z|>2.5 within category peer group OR |variance_pct| ≥ 30)\n")
GT = set("BUD-00237 BUD-00189 BUD-00176 BUD-00005 BUD-00190 BUD-00285 BUD-00213 BUD-00267 BUD-00160 BUD-00156 BUD-00228 BUD-00293 BUD-00087 BUD-00202 BUD-00116 BUD-00028 BUD-00241".split())
d = a.copy(); d["z"] = 0.0
for c, g in d.groupby("budget_category"):
    m = g.variance_pct.median(); mad = (g.variance_pct - m).abs().median()
    if mad > 0: d.loc[g.index, "z"] = 0.6745 * (g.variance_pct - m) / mad
f = d[(d.z.abs() > 2.5) | (d.variance_pct.abs() >= 30)]
src = set(f.source_record_id.dropna())
P(f"- flagged monthly rows: {len(f)}; non-synthetic source records flagged: {len(src)}; GT hit: {len(GT & src)}/17; extra non-synthetic source records: {sorted(src - GT)}; synthetic rows flagged: {int(f.is_synthetic.sum())}")
